### ISSUE TITLE
Copy files task

### ISSUE THREAD

**Issue by ghost** [romanschejbal/gassetic#36]
Hi @crossborne!

I try to create a copy task (or symlink)  to use fontawesome, but I failed on gassetic.yml configuration.

I would like copy/symlink some files in  the same specific directory.
Sample : 
I would like all my fonts are copied in web/vendor/compiled/fonts

```
web/vendor/font-awesome/fonts/FontAwesome.otf => web/vendor/compiled/fonts/FontAwesome.otf
web/vendor/font-awesome/fonts/fontawesome-webfont.eot => web/vendor/compiled/fonts/fontawesome-webfont.eot
web/vendor/font-awesome/fonts/fontawesome-webfont.svg => web/vendor/compiled/fonts/fontawesome-webfont.svg
```

It's possible with the current last gassetic version ? How ?
I have already install gulp-copy and gulp-sym.

Thank you for your help :)

**Comment by lgiraudel** [comment]
Hello,

Is the `autoRenaming` parameter still working ? I have some trouble (for FontAwesome too) because Gassetic renames all my fonts files after moving it to the output folder.

How can I avoid this renaming step ? I tried to create a custom task to remove the `_[1..n]` prefix, unfortunately the tasks are processed before this renaming step.

**Comment by lgiraudel** [comment]
Nevermind, it's still working perfectly :)

**Comment by KhanMaytok** [comment]
It only copy one level files, not recursively :(
